# Settings
settings:
  interval: 5 # in seconds
  log_path: logs/access.log # path to logfile

# ClickHouse credentials
clickhouse:
 db: metrics
 table: nginx
 host: 172.17.0.2
 port: 8123
 credentials:
  user: default
  password:
 columns:
   RemoteAddr: remote_addr
   RemoteUser: remote_user
   TimeLocal: time_local
   Request: request
   Status: status
   BytesSent: body_bytes_sent
   HttpReferer: http_referer
   HttpUserAgent: http_user_agent

# NGINX
nginx:
  log_type: main
  log_format: $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"